#!/usr/bin/env python3
"""
Generate crontab configuration from config.yaml
This ensures the crontab uses correct paths and intervals from the config
"""

import yaml
import sys
from pathlib import Path


def load_config(config_path):
    """Load configuration from YAML file"""
    with open(config_path, 'r') as f:
        return yaml.safe_load(f)


def interval_to_cron(minutes):
    """Convert interval in minutes to cron expression"""
    if minutes <= 0 or minutes > 59:
        raise ValueError(f"Invalid interval: {minutes} minutes")
    return f"*/{minutes}"


def generate_crontab(project_dir, config):
    """Generate crontab content from config"""

    intervals = config['collection_intervals']
    working_hours = config['working_hours']

    # Convert intervals to cron expressions
    working_interval = interval_to_cron(intervals['weekday_working_hours'])
    non_working_interval = interval_to_cron(intervals['weekday_non_working_hours'])
    weekend_interval = interval_to_cron(intervals['weekend'])

    # Build hour ranges for working hours
    working_hours_range = f"{working_hours['start']}-{working_hours['end']-1}"
    non_working_hours_range = f"0-{working_hours['start']-1},{working_hours['end']}-23"

    # Paths to wrapper scripts
    bkk_script = f"{project_dir}/scripts/run_bkk_collector.sh"
    weather_script = f"{project_dir}/scripts/run_weather_collector.sh"

    crontab_content = f"""# BKK Transit Analytics - Cron Schedule Configuration
#
# AUTO-GENERATED by scripts/generate_crontab.py
# To regenerate: python scripts/generate_crontab.py
# To install: crontab scripts/crontab.txt
# To view: crontab -l
#
# Configuration:
# - Project directory: {project_dir}
# - Weekday working hours interval: {intervals['weekday_working_hours']} minutes
# - Weekday non-working hours interval: {intervals['weekday_non_working_hours']} minutes
# - Weekend interval: {intervals['weekend']} minutes

# ============================================================================
# BKK DATA COLLECTION
# ============================================================================

# Weekdays (Mon-Thu) during working hours ({working_hours['start']}:00-{working_hours['end']-1}:59)
{working_interval} {working_hours_range} * * 1-4 {bkk_script}

# Weekdays (Mon-Thu) outside working hours
{non_working_interval} {non_working_hours_range} * * 1-4 {bkk_script}

# Weekends (Fri-Sun) - all day
{weekend_interval} * * * 5-7 {bkk_script}

# ============================================================================
# WEATHER DATA COLLECTION
# ============================================================================

# Run twice daily at 9:00 and 21:00 (collects weather for last 2 days)
0 9,21 * * * {weather_script}

# ============================================================================
# NOTES
# ============================================================================
#
# To update the schedule:
# 1. Edit config/config.yaml (collection_intervals section)
# 2. Run: python scripts/generate_crontab.py
# 3. Install: crontab scripts/crontab.txt
#
# Logs:
# - Application logs: logs/collector.log
# - Cron execution logs: logs/cron_bkk.log, logs/cron_weather.log
#
# Monitoring:
# - Run: python src/monitor.py
# - Check logs: tail -f logs/cron_*.log
#
"""
    return crontab_content


def main():
    """Main entry point"""
    # Determine project directory (parent of scripts directory)
    script_dir = Path(__file__).parent.resolve()
    project_dir = script_dir.parent

    # Load config
    config_path = project_dir / "config" / "config.yaml"

    if not config_path.exists():
        print(f"ERROR: Config file not found: {config_path}")
        print("Please create config.yaml from config.yaml.template")
        sys.exit(1)

    try:
        config = load_config(config_path)
    except Exception as e:
        print(f"ERROR: Failed to load config: {e}")
        sys.exit(1)

    # Generate crontab
    try:
        crontab_content = generate_crontab(str(project_dir), config)
    except Exception as e:
        print(f"ERROR: Failed to generate crontab: {e}")
        sys.exit(1)

    # Write to file
    output_path = script_dir / "crontab.txt"
    try:
        with open(output_path, 'w') as f:
            f.write(crontab_content)
        print(f"✓ Generated crontab: {output_path}")
        print(f"✓ Project directory: {project_dir}")
        print(f"\nTo install:")
        print(f"  crontab {output_path}")
    except Exception as e:
        print(f"ERROR: Failed to write crontab: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
